name: Release Collection

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and Publish Collection

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/rtfm/ai_modules

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install --system ansible-core

      - name: Update version in galaxy.yml
        run: |
          cd ansible_collections/rtfm/ai_modules
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION=${VERSION#v}  # Remove 'v' prefix if present
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          sed -i "s/version: .*/version: ${VERSION}/" galaxy.yml
          echo "Updated version to: ${VERSION}"
          cat galaxy.yml | grep version

      - name: Build collection
        run: |
          cd ansible_collections/rtfm/ai_modules
          ansible-galaxy collection build --force

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection-release
          path: ansible_collections/rtfm/ai_modules/rtfm-ai_modules-*.tar.gz

      # Uncomment when ready to publish to Ansible Galaxy
      # - name: Publish to Ansible Galaxy
      #   run: |
      #     cd ansible_collections/rtfm/ai_modules
      #     ansible-galaxy collection publish rtfm-ai_modules-*.tar.gz --api-key=${{ secrets.GALAXY_API_KEY }}

      - name: Create GitHub Release Assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ansible_collections/rtfm/ai_modules/rtfm-ai_modules-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}